[package]
name = "lib-polar-h10"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.5"
futures = "0.3.31"
tokio = "1.40.0"
uuid = "1.10.0"

[features]
tokio-rt = ["tokio/rt-multi-thread", "tokio/macros"]